### ISSUE TITLE
Dans vérification pour la correction du projet:

### ISSUE THREAD

**Issue by ZackTO** [CollegeBoreal/INF1006-202-20A-01#1]
Dans la liste de vérificatgion pour le peojet, quelle est la différence entre la rubrique rapports et la rubrique les requêtes SQL. Il me semble qu'il s'agit de la même chose. Quelle est la différence par exemple entre 1 rapport de deux tables avec filtres sur plusieurs critéres et une requête avec deux tables avec filtres sur plusieurs critéres?

**Comment by b300098957** [comment]
[3.DDL-DCL/documentation](https://github.com/CollegeBoreal/INF1006-202-20A-01/tree/master/3.DDL-DCL/documentation)

:one: Rubrique rapports et Rubrique requêtes SQL

:bookmark: Imprimer le nom et le montant de la facture totale des personnes habitant la ville de Lubumbashi - **Rapport** :+1:

**SQL** :+1:
```SQL
SELECT city.city, customer.last_name, SUM(payment.amount) FROM city 
JOIN address USING (city_id) 
JOIN customer USING (address_id)
JOIN payment USING (customer_id)
WHERE city = "Lubumbashi"
GROUP BY city.city, customer.last_name;
```

C'est en effet la même chose:
- [ ]  le rapport est la demande émanant d'un client et 
- [ ] la requête est la réponse fournie par le Développeur/fournisseur

:two: Filtres et critères

```
1 rapport de deux tables avec filtres sur plusieurs critéres et 
1 requête avec deux tables avec filtres sur plusieurs critéres
```

C'est une ambiguïté qui doit être corrigée si c'est dans l'énoncé
